CREATE DATABASE inlock_games_dbFirst_manha

USE inlock_games_dbFirst_manha


CREATE TABLE Estudio
(
	IdEstudio UNIQUEIDENTIFIER  PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL
)

CREATE TABLE Jogo
(
	IdJogo UNIQUEIDENTIFIER PRIMARY KEY,
	IdEstudio UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Estudio(IdEstudio),
	Nome VARCHAR(100) NOT NULL,
	Descricao VARCHAR(100) NOT NULL,
	DataLancamento DATE NOT NULL,
	Valor SMALLMONEY NOT NULL
)

CREATE TABLE TiposUsuario
(
	IdTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY,
	Titulo VARCHAR(100) NOT NULL
)

CREATE TABLE Usuario
(
	IdUsuario UNIQUEIDENTIFIER PRIMARY KEY,
	IdTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TiposUsuario(IdTipoUsuario),
	Email VARCHAR(100) NOT NULL,
	Senha VARCHAR(100) NOT NULL
)



INSERT INTO Estudio
VALUES (NEWID(),'Senai'),(NEWID(),'SESI'),(NEWID(),'SEBRAE')


INSERT INTO Jogo
VALUES (NEWID(),'606AC8A8-592C-4712-BEF9-906D6BADCE91', 'Ping Pong', 'Jogo Legal', '2021-01-04', 500), 
		(NEWID(),'606AC8A8-592C-4712-BEF9-906D6BADCE91', 'Fifa', 'futebol', '2023-03-04',500)  


INSERT INTO TiposUsuario
VALUES (NEWID(), 'Administrador'),(NEWID(), 'Comum')


INSERT INTO Usuario
VALUES (NEWID(), '4CA06BA7-0E4E-479C-817C-93B62BE03132', 'comum@email.com', 'comum'),
		(NEWID(), '83A47827-73FB-4B3D-9DF6-B6FC56A125C2', 'admin@email.com', 'admin')
